OpenUpSA/muni-portal-frontend

src/service-worker.js

so that they can be found if you're offline

Add network-first routing for services listing

---

netlify.toml
package.json
src/js/components/pages.js
src/js/components/tabs.js
src/js/index.js
src/service-worker.js

Router configuration was calling redirect instead of creating an anonymous
function that woud redirect when called"

Switch to real paths (not #/path) for SEO and fix router initialisation

---

src/js/api.js
src/js/components/tabs.js
src/js/index.js

Add my muni tab and tab content.
Couple of issues.
- It only ever shows one tab at a time. Not sure how we want to build the navigation so that it shows both the services and my-muni tabs
- The tab title is not updated i.e. if you go to `http://127.0.0.1:8080/my-municipality/` and then to `http://127.0.0.1:8080/services/` the tab still says "My Muni". The icon also does not change. Could it be because the constructor is only called the first time and we need to update these two items inside `show`?
Let me know your thoughts.
fix #18

add my muni page

---

.eslintrc.json
.gitignore
src/index.html
src/js/index.js
src/js/webflow/import.js

Add Google tag manager and set data layer data on routes.
I tested this with a property I have set-up and used the debug view of GTM.
I could see each of the `dataLayer` pushes happen as I navigated around the app
fix #30

feat: google tag manager

---

package.json
src/js/index.js
yarn.lock

Add conditional Sentry error logging at 100% sample rate
Proof that it works 😄 
fix #32

feat: sentry

---

.gitignore
src/js/components/link-block.js
src/js/components/pages.js
src/js/components/service-point.js
src/js/index.js

Add service points and pages
fix #15

feat: service points and pages

---

src/js/components/tab-item.js
src/js/index.js

Use composite icon for service tab.
Update logic in `tab-item.js` to create a special case for this icon
fix #39

services tab icon

---

src/js/components/pages.js

Show role/job title for individual on profile page
See screenshot below (NOTE: we need to add a `24px` margin to the bottom of profile images)
fix #43

show role/job title

---

src/js/components/basic-block.js
src/js/components/pages.js

Show office hours when specified on service page.
Enhance basic block to handle both plain text and html
fix #48

feat: office hours

---

src/js/components/pages.js

Move party affiliation rending to person page not the general page class
fix #54

refactor: party affiliation

---

src/js/api.js
src/js/components/user-registration.js
src/js/index.js

Add base for user registration to MyMuni.
As I say "base" 😄  We probably want to do more work and offer better feedback depending on the type of error. But this is a start. I also create the entire form using jQuery and add the relevant classes.
Let me know your thoughts.
This uses the relevant element from `.styles`
This uses the relevant element from `.styles`
fix #56

fix: user registration

---

src/js/api.js
src/js/components/user-registration-verify.js
src/js/index.js

Add verify user modal and logic to verify user based on query string

feat: verify user

---

src/js/api.js
src/js/components/account/forgot-password.js
src/js/components/user-registration.js
src/js/index.js
src/js/utils/element-factory.js

Enabled the ability to request a password reset link

feat: reset password

---

src/js/api.js
src/js/components/atoms/date-time.js
src/js/components/pages.js
src/js/index.js

Add NoticeIndex page as well as page for displaying individual notices
fix #78

fix: add notice index and notice pages

---

src/js/components/pages.js
src/js/index.js

Refactor based on feedback regarding the Notices index in individual pages

fix: updates to notices

---

src/js/components/notifications/index.js

Test support for `Notification`, `serviceWorker`, and `PushManager`

fix: strengthen requirements for notifications

---

netlify.toml

Hotfix: broken DEFAULT_BASE_API_URL urls in netlify.toml

---

src/js/index.js

Register service worker for staging and sandbox environments

---

README.md

Please ignore the branch name.
This PR just adds docs.

Add docs about staging and sandbox to README.md

---

src/index.html
src/js/webflow/import.js

Use PUSHPAD_PROJECT_ID in parcel's deployment build

---

.eslintrc.js
src/js/components/account/login.js
src/js/components/account/molecules/quick-links-block.js
src/js/components/atoms/basic-non-link-block.js

as a new user sent to the login screenI would like to find the registration screen so that I can create an account

fix: add register link to login view

---

README.md
src/js/components/pages.js
src/js/components/rich-text.js
src/js/index.js

Call Webflow init from the relevant Page

fix: call webflow init from page level

---

src/js/components/service-requests/submit-service-request.js

Change the suburb input field to town in the UI.

fix: change suburb to town

---

src/js/components/service-requests/closed-service-requests.js
src/js/components/service-requests/current-service-requests.js

- fix: fix excessively long title
- same for closed requests

sr fix long titles

---

src/js/components/service-requests/submit-service-request.js

Fixes missing input fields on submit new service request.

fix: input fields in service request

---

src/js/components/constants.js
src/js/components/service-requests/current-service-requests.js

Change the in_progress status label to assigned and use the copy "Assigned to responsible person" in the UI

fix: change in_progress to assigned

---

.eslintrc.json
src/js/components/account/user-settings.js
src/js/components/molecules/checkbox.js

Add the ability to enable in-app notifications from settings.

fix: add subscribe to notification to settings

---

src/js/components/service-requests/service-request-submitted.js
src/js/components/service-requests/submit-service-request.js

Fix service requests submission bugs

---

package.json
src/js/components/service-requests/submit-service-request.js

Add front-end form validation to the service request form

fix: service request form validation

---

src/js/components/contact.js
src/js/components/pages.js
src/js/components/rich-text.js
src/js/components/service-requests/images.js
src/js/components/service-requests/service-request-map.js
src/js/components/service-requests/submit-service-request.js
src/js/index.js
src/js/utils/analytics.js
src/js/utils/element-factory.js
src/js/utils/menu.js

Add events as per https://trello.com/c/E7cA31Kp/239-as-openup-i-would-like-to-know-if-people-are-using-the-interactive-elements-of-the-app-so-that-i-can-tell-whether-it-is-engaging

fix: GA custom events

---

src/js/components/account/user-registration.js

https://trello.com/c/rUqsG6bX/263-expect-registration-mail-as-a-user-i-would-like-to-know-that-i-will-receive-an-email-and-need-to-complete-registration-by-clicki

Update successful user registration message

---

src/js/components/pages.js
src/js/components/service-requests/closed-service-requests.js
src/js/components/service-requests/current-service-requests.js
src/js/components/service-requests/images.js
src/js/components/service-requests/index.js
src/js/components/service-requests/service-request-detail.js
src/js/components/service-requests/service-request-submitted.js
src/js/components/service-requests/submit-service-request.js
src/js/index.js
src/js/utils/menu.js

(or closest variation depending on context)

Rename all user-visible occurences of "Service request" to "Complaints and requests"

---

src/js/components/account/forgot-password.js
src/js/components/account/reset-password.js
src/js/components/account/user-registration-verify.js
src/js/components/account/user-registration.js
src/js/components/account/user-settings.js
src/js/components/constants.js
src/js/utils/menu.js

https://trello.com/c/Y6QmPWMj/264-contact-support-notices-as-a-user-i-would-like-to-know-how-to-contact-support

Clickable mail link for "contact support" messages

---

package.json
src/js/swRegistration.js
src/service-worker.js
yarn.lock

Improve how service updates are handled.

fix: service worker updates for improved updates

---

src/js/components/account/user-registration.js
src/js/components/pages.js
src/js/utils/element-factory.js

API PR: https://github.com/OpenUpSA/muni-portal-backend/pull/85
Trello: https://trello.com/c/0typVj4g

Add privacy policy & require checkbox before submission

---

src/js/components/account/user-registration.js
src/js/components/pages.js
src/js/utils/element-factory.js

Reverts OpenUpSA/muni-portal-frontend#147

Revert "Add privacy policy & require checkbox before submission"

---

src/js/components/account/forgot-password.js

Trello: https://trello.com/c/ce9F5LiB

Fix broken error message shown to user on forgot password page

---

src/js/components/service-requests/submit-service-request.js

Trello: https://trello.com/c/lw76rdqG

Show the user an error if the attachment upload fails

---

src/js/components/contact.js

Update event name for contact event types

fix: update to contact evet types

---

src/css/citizen-engagement-app.css
src/css/components.css
src/index.html
src/js/citizen-engagement-app.js

Import latest webflow export: 2021-07-06
Remove early app preview from logo when we go live

chore: import latest webflow

---

src/js/components/account/user-registration.js
src/js/components/pages.js
src/js/utils/element-factory.js

Reverts OpenUpSA/muni-portal-frontend#152
This is effectively the original PR #147 but we had to revert it in #152 as it wasn't ready to be merged.
Merge this one when the privacy policy has been added to the backend.

Add privacy notice & require checkbox before submission (#2)
